CREATE TABLE IF NOT EXISTS `ele_store_inventory_batch_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  `task_no` varchar(64) NOT NULL COMMENT '任务编号',
  `source_type` varchar(32) NOT NULL COMMENT '来源类型',
  `scope` varchar(32) NOT NULL COMMENT '任务范围',
  `status` varchar(32) NOT NULL COMMENT '任务状态',
  `total_store_count` int NOT NULL DEFAULT '0' COMMENT '总门店数',
  `finished_store_count` int NOT NULL DEFAULT '0' COMMENT '已完成门店数',
  `total_batch_count` int NOT NULL DEFAULT '0' COMMENT '总批次数',
  `finished_batch_count` int NOT NULL DEFAULT '0' COMMENT '已完成批次数',
  `total_sku_count` int NOT NULL DEFAULT '0' COMMENT '总SKU数',
  `formal_success_count` int NOT NULL DEFAULT '0' COMMENT '正式落库数',
  `shadow_success_count` int NOT NULL DEFAULT '0' COMMENT '影子落库数',
  `governance_count` int NOT NULL DEFAULT '0' COMMENT '治理数',
  `failure_count` int NOT NULL DEFAULT '0' COMMENT '失败数',
  `error_msg` varchar(1024) DEFAULT NULL COMMENT '错误信息',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ele_store_inventory_batch_task_no` (`task_no`),
  KEY `idx_ele_store_inventory_batch_task_scope_status` (`scope`,`status`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='饿了么门店库存批量任务主表';

CREATE TABLE IF NOT EXISTS `ele_store_inventory_batch_task_store` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `task_no` varchar(64) NOT NULL COMMENT '任务编号',
  `store_id` varchar(64) DEFAULT NULL COMMENT '本地门店ID',
  `store_name` varchar(128) DEFAULT NULL COMMENT '门店名称',
  `merchant_code` varchar(64) DEFAULT NULL COMMENT '商家编码',
  `erp_store_code` varchar(64) DEFAULT NULL COMMENT 'ERP门店编码',
  `platform_store_id` varchar(64) DEFAULT NULL COMMENT '平台门店ID',
  `status` varchar(32) NOT NULL COMMENT '门店任务状态',
  `current_batch_no` int NOT NULL DEFAULT '0' COMMENT '当前批次号',
  `total_batch_no` int NOT NULL DEFAULT '0' COMMENT '总批次数',
  `total_sku_count` int NOT NULL DEFAULT '0' COMMENT '总SKU数',
  `formal_success_count` int NOT NULL DEFAULT '0' COMMENT '正式落库数',
  `shadow_success_count` int NOT NULL DEFAULT '0' COMMENT '影子落库数',
  `governance_count` int NOT NULL DEFAULT '0' COMMENT '治理数',
  `failure_count` int NOT NULL DEFAULT '0' COMMENT '失败数',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '重试次数',
  `error_msg` varchar(1024) DEFAULT NULL COMMENT '错误信息',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_ele_store_inventory_batch_task_store_task` (`task_id`,`deleted`),
  KEY `idx_ele_store_inventory_batch_task_store_status` (`status`,`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='饿了么门店库存批量任务门店子表';
