CREATE TABLE IF NOT EXISTS `ele_store_inventory_shadow` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  `platform_id` bigint NOT NULL COMMENT '平台ID',
  `merchant_code` varchar(64) NOT NULL COMMENT '商家编码',
  `erp_store_code` varchar(64) NOT NULL COMMENT 'ERP门店编码',
  `platform_store_id` varchar(64) DEFAULT NULL COMMENT '平台门店ID',
  `store_id` varchar(64) DEFAULT NULL COMMENT '本地门店ID',
  `sku_code` varchar(128) DEFAULT NULL COMMENT '平台SKU编码',
  `sub_sku_code` varchar(128) DEFAULT NULL COMMENT '平台子SKU编码',
  `matched_product_sku_id` varchar(64) DEFAULT NULL COMMENT '命中的本地SKU ID',
  `matched_store_product_id` varchar(64) DEFAULT NULL COMMENT '命中的本地门店商品ID',
  `available_for_sale` int DEFAULT NULL COMMENT '可售库存',
  `reserved_amount` int DEFAULT NULL COMMENT '预留库存',
  `physical_stock_total_amount` int DEFAULT NULL COMMENT '物理总库存',
  `physical_stock_available_amount` int DEFAULT NULL COMMENT '物理可用库存',
  `physical_stock_occupied_amount` int DEFAULT NULL COMMENT '物理占用库存',
  `physical_stock_intransit_amount` int DEFAULT NULL COMMENT '物理在途库存',
  `owner_code` varchar(64) DEFAULT NULL COMMENT '货主编码',
  `owner_name` varchar(128) DEFAULT NULL COMMENT '货主名称',
  `match_status` varchar(32) NOT NULL COMMENT '匹配状态',
  `reason_code` varchar(64) NOT NULL COMMENT '原因编码',
  `reason_msg` varchar(255) NOT NULL COMMENT '原因描述',
  `raw_payload` text COMMENT '原始响应快照',
  `last_query_time` datetime NOT NULL COMMENT '最后查询时间',
  `unique_deleted` bigint NOT NULL DEFAULT '0' COMMENT '逻辑唯一删除标记',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ele_store_inventory_shadow_sku` (`platform_id`,`merchant_code`,`erp_store_code`,`sku_code`,`unique_deleted`),
  UNIQUE KEY `uk_ele_store_inventory_shadow_sub_sku` (`platform_id`,`merchant_code`,`erp_store_code`,`sub_sku_code`,`unique_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='饿了么门店库存影子表';

CREATE TABLE IF NOT EXISTS `ele_store_inventory_governance_pool` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  `platform_id` bigint NOT NULL COMMENT '平台ID',
  `merchant_code` varchar(64) NOT NULL COMMENT '商家编码',
  `erp_store_code` varchar(64) NOT NULL COMMENT 'ERP门店编码',
  `platform_store_id` varchar(64) DEFAULT NULL COMMENT '平台门店ID',
  `store_id` varchar(64) DEFAULT NULL COMMENT '本地门店ID',
  `sku_code` varchar(128) DEFAULT NULL COMMENT '平台SKU编码',
  `sub_sku_code` varchar(128) DEFAULT NULL COMMENT '平台子SKU编码',
  `inventory_shadow_id` bigint DEFAULT NULL COMMENT '关联影子库存ID',
  `reason_code` varchar(64) NOT NULL COMMENT '原因编码',
  `reason_msg` varchar(255) NOT NULL COMMENT '原因描述',
  `process_status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '处理状态',
  `raw_payload` text COMMENT '原始响应快照',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `unique_deleted` bigint NOT NULL DEFAULT '0' COMMENT '逻辑唯一删除标记',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ele_store_inventory_governance_sku` (`platform_id`,`merchant_code`,`erp_store_code`,`sku_code`,`reason_code`,`unique_deleted`),
  UNIQUE KEY `uk_ele_store_inventory_governance_sub_sku` (`platform_id`,`merchant_code`,`erp_store_code`,`sub_sku_code`,`reason_code`,`unique_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='饿了么门店库存治理池';
