DELETE FROM `product_upc_table`;
DELETE FROM `product_sku_table`;
DELETE FROM `product_spu_table`;
DELETE FROM `tag_object_relation`;
DELETE FROM `tag_virtual`;
DELETE FROM `tag_value`;
DELETE FROM `tag_dimension`;
DELETE FROM `biz_external_api_call_log`;
DELETE FROM `ele_store_goods_shadow`;
