CREATE TABLE IF NOT EXISTS `biz_external_api_call_log` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `platform_code` varchar(32) NOT NULL,
    `api_code` varchar(64) NOT NULL,
    `api_name` varchar(128) DEFAULT NULL,
    `biz_type` varchar(32) DEFAULT NULL,
    `biz_id` varchar(64) DEFAULT NULL,
    `biz_no` varchar(64) DEFAULT NULL,
    `trace_id` varchar(64) DEFAULT NULL,
    `external_trace_id` varchar(64) DEFAULT NULL,
    `request_id` varchar(64) DEFAULT NULL,
    `request_url` varchar(255) DEFAULT NULL,
    `request_method` varchar(16) DEFAULT NULL,
    `request_body` clob DEFAULT NULL,
    `response_body` clob DEFAULT NULL,
    `success` bit NOT NULL DEFAULT FALSE,
    `result_code` varchar(64) DEFAULT NULL,
    `result_msg` varchar(512) DEFAULT NULL,
    `duration_ms` int DEFAULT NULL,
    `merchant_code` varchar(64) DEFAULT NULL,
    `platform_store_id` varchar(64) DEFAULT NULL,
    `erp_store_code` varchar(64) DEFAULT NULL,
    `order_id` varchar(64) DEFAULT NULL,
    `channel_order_id` varchar(64) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
);
CREATE INDEX IF NOT EXISTS `idx_biz_external_api_call_log_trace_id` ON `biz_external_api_call_log` (`trace_id`);
CREATE INDEX IF NOT EXISTS `idx_biz_external_api_call_log_external_trace_id` ON `biz_external_api_call_log` (`external_trace_id`);

CREATE TABLE IF NOT EXISTS `tag_dimension` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `domain_type` varchar(32) NOT NULL,
    `parent_id` bigint NOT NULL DEFAULT 0,
    `level` tinyint NOT NULL,
    `name` varchar(100) NOT NULL,
    `code` varchar(100) NOT NULL,
    `sort` int NOT NULL DEFAULT 0,
    `status` tinyint NOT NULL DEFAULT 1,
    `description` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `unique_deleted` bigint NOT NULL DEFAULT 0,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_tag_dimension_parent_code` ON `tag_dimension` (`tenant_id`, `domain_type`, `parent_id`, `code`, `unique_deleted`);
CREATE INDEX IF NOT EXISTS `idx_tag_dimension_parent` ON `tag_dimension` (`parent_id`);

CREATE TABLE IF NOT EXISTS `tag_value` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `dimension_id` bigint NOT NULL,
    `name` varchar(100) NOT NULL,
    `code` varchar(100) NOT NULL,
    `tag_method` varchar(32) NOT NULL,
    `data_source` varchar(200) DEFAULT NULL,
    `update_frequency` varchar(100) DEFAULT NULL,
    `logic_description` varchar(1000) DEFAULT NULL,
    `sort` int NOT NULL DEFAULT 0,
    `status` tinyint NOT NULL DEFAULT 1,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `unique_deleted` bigint NOT NULL DEFAULT 0,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_tag_value_dimension_code` ON `tag_value` (`tenant_id`, `dimension_id`, `code`, `unique_deleted`);
CREATE INDEX IF NOT EXISTS `idx_tag_value_dimension` ON `tag_value` (`dimension_id`);

CREATE TABLE IF NOT EXISTS `tag_virtual` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `domain_type` varchar(32) NOT NULL,
    `name` varchar(100) NOT NULL,
    `code` varchar(100) NOT NULL,
    `expression_json` clob NOT NULL,
    `expression_summary` varchar(1000) DEFAULT NULL,
    `usage_scenario` varchar(500) DEFAULT NULL,
    `status` tinyint NOT NULL DEFAULT 1,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `unique_deleted` bigint NOT NULL DEFAULT 0,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_tag_virtual_domain_code` ON `tag_virtual` (`tenant_id`, `domain_type`, `code`, `unique_deleted`);
