CREATE TABLE IF NOT EXISTS `biz_external_api_call_log` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `platform_code` varchar(32) NOT NULL,
    `api_code` varchar(64) NOT NULL,
    `api_name` varchar(128) DEFAULT NULL,
    `biz_type` varchar(32) DEFAULT NULL,
    `biz_id` varchar(64) DEFAULT NULL,
    `biz_no` varchar(64) DEFAULT NULL,
    `trace_id` varchar(64) DEFAULT NULL,
    `external_trace_id` varchar(64) DEFAULT NULL,
    `request_id` varchar(64) DEFAULT NULL,
    `request_url` varchar(255) DEFAULT NULL,
    `request_method` varchar(16) DEFAULT NULL,
    `request_body` clob DEFAULT NULL,
    `response_body` clob DEFAULT NULL,
    `success` bit NOT NULL DEFAULT FALSE,
    `result_code` varchar(64) DEFAULT NULL,
    `result_msg` varchar(512) DEFAULT NULL,
    `duration_ms` int DEFAULT NULL,
    `merchant_code` varchar(64) DEFAULT NULL,
    `platform_store_id` varchar(64) DEFAULT NULL,
    `erp_store_code` varchar(64) DEFAULT NULL,
    `order_id` varchar(64) DEFAULT NULL,
    `channel_order_id` varchar(64) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
);
CREATE INDEX IF NOT EXISTS `idx_biz_external_api_call_log_trace_id` ON `biz_external_api_call_log` (`trace_id`);
CREATE INDEX IF NOT EXISTS `idx_biz_external_api_call_log_external_trace_id` ON `biz_external_api_call_log` (`external_trace_id`);

CREATE TABLE IF NOT EXISTS `product_spu_table` (
    `product_spu_id` bigint NOT NULL,
    `product_spu_code` varchar(100) NOT NULL,
    `product_spu_name` varchar(255) NOT NULL,
    `product_brand` varchar(100) DEFAULT NULL,
    `category_id` bigint DEFAULT NULL,
    `product_origin` varchar(255) DEFAULT NULL,
    `product_manufacturer` varchar(255) DEFAULT NULL,
    `product_spec_template` json DEFAULT NULL,
    `product_image_url` varchar(500) DEFAULT NULL,
    `product_detail_images` clob DEFAULT NULL,
    `product_description` clob DEFAULT NULL,
    `product_spu_status` tinyint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`product_spu_id`)
);

CREATE TABLE IF NOT EXISTS `product_sku_table` (
    `product_sku_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `product_sku_code` varchar(100) NOT NULL,
    `product_sku_name` varchar(255) DEFAULT NULL,
    `product_spu_id` bigint NOT NULL,
    `product_sku_ean` varchar(64) DEFAULT NULL,
    `product_weight` decimal(24, 6) DEFAULT NULL,
    `product_weight_unit` varchar(32) DEFAULT NULL,
    `product_length` decimal(24, 6) DEFAULT NULL,
    `product_width` decimal(24, 6) DEFAULT NULL,
    `product_height` decimal(24, 6) DEFAULT NULL,
    `product_cost_price` decimal(24, 6) DEFAULT NULL,
    `product_retail_price` decimal(24, 6) DEFAULT NULL,
    `product_image_url` varchar(500) DEFAULT NULL,
    `product_sku_status` tinyint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`product_sku_id`)
);

CREATE TABLE IF NOT EXISTS `product_upc_table` (
    `product_upc_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `product_sku_id` bigint NOT NULL,
    `product_upc_type` varchar(64) DEFAULT NULL,
    `product_upc_value` varchar(255) DEFAULT NULL,
    `product_upc_is_primary` tinyint DEFAULT NULL,
    `product_upc_status` tinyint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`product_upc_id`)
);

CREATE TABLE IF NOT EXISTS `tag_dimension` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `domain_type` varchar(32) NOT NULL,
    `parent_id` bigint NOT NULL DEFAULT 0,
    `level` tinyint NOT NULL,
    `name` varchar(100) NOT NULL,
    `code` varchar(100) NOT NULL,
    `sort` int NOT NULL DEFAULT 0,
    `status` tinyint NOT NULL DEFAULT 1,
    `description` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `unique_deleted` bigint NOT NULL DEFAULT 0,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_tag_dimension_parent_code` ON `tag_dimension` (`tenant_id`, `domain_type`, `parent_id`, `code`, `unique_deleted`);
CREATE INDEX IF NOT EXISTS `idx_tag_dimension_parent` ON `tag_dimension` (`parent_id`);

CREATE TABLE IF NOT EXISTS `tag_value` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `dimension_id` bigint NOT NULL,
    `name` varchar(100) NOT NULL,
    `code` varchar(100) NOT NULL,
    `tag_method` varchar(32) NOT NULL,
    `data_source` varchar(200) DEFAULT NULL,
    `update_frequency` varchar(100) DEFAULT NULL,
    `logic_description` varchar(1000) DEFAULT NULL,
    `sort` int NOT NULL DEFAULT 0,
    `status` tinyint NOT NULL DEFAULT 1,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `unique_deleted` bigint NOT NULL DEFAULT 0,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_tag_value_dimension_code` ON `tag_value` (`tenant_id`, `dimension_id`, `code`, `unique_deleted`);
CREATE INDEX IF NOT EXISTS `idx_tag_value_dimension` ON `tag_value` (`dimension_id`);

CREATE TABLE IF NOT EXISTS `tag_virtual` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `domain_type` varchar(32) NOT NULL,
    `name` varchar(100) NOT NULL,
    `code` varchar(100) NOT NULL,
    `expression_json` clob NOT NULL,
    `expression_summary` varchar(1000) DEFAULT NULL,
    `usage_scenario` varchar(500) DEFAULT NULL,
    `status` tinyint NOT NULL DEFAULT 1,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `unique_deleted` bigint NOT NULL DEFAULT 0,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_tag_virtual_domain_code` ON `tag_virtual` (`tenant_id`, `domain_type`, `code`, `unique_deleted`);

CREATE TABLE IF NOT EXISTS `tag_object_relation` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `domain_type` varchar(32) NOT NULL,
    `object_type` varchar(32) NOT NULL,
    `object_id` bigint NOT NULL,
    `tag_value_id` bigint NOT NULL,
    `source_type` varchar(32) NOT NULL,
    `source_ref` varchar(64) NOT NULL DEFAULT '',
    `status` tinyint NOT NULL DEFAULT 1,
    `effective_time` timestamp DEFAULT NULL,
    `expire_time` timestamp DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `unique_deleted` bigint NOT NULL DEFAULT 0,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_tag_object_relation_biz` ON `tag_object_relation` (`tenant_id`, `domain_type`, `object_type`, `object_id`, `tag_value_id`, `source_type`, `source_ref`, `unique_deleted`);
CREATE INDEX IF NOT EXISTS `idx_tag_object_relation_object` ON `tag_object_relation` (`tenant_id`, `object_type`, `object_id`, `status`);
CREATE INDEX IF NOT EXISTS `idx_tag_object_relation_tag_value` ON `tag_object_relation` (`tenant_id`, `tag_value_id`, `status`);
CREATE INDEX IF NOT EXISTS `idx_tag_object_relation_domain_status` ON `tag_object_relation` (`tenant_id`, `domain_type`, `object_type`, `status`);

CREATE TABLE IF NOT EXISTS `ele_store_goods_shadow` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `platform_id` bigint NOT NULL,
    `merchant_code` varchar(64) NOT NULL,
    `erp_store_code` varchar(64) NOT NULL,
    `platform_store_id` varchar(64) DEFAULT NULL,
    `store_id` varchar(64) DEFAULT NULL,
    `spu_code` varchar(100) DEFAULT NULL,
    `sku_code` varchar(100) NOT NULL,
    `sub_sku_code` varchar(100) DEFAULT NULL,
    `title` varchar(255) DEFAULT NULL,
    `main_pic` varchar(500) DEFAULT NULL,
    `sub_pics` clob DEFAULT NULL,
    `front_category` clob DEFAULT NULL,
    `brand_name` varchar(128) DEFAULT NULL,
    `specification` varchar(255) DEFAULT NULL,
    `sale_price` decimal(24, 6) DEFAULT NULL,
    `pos_status` varchar(32) DEFAULT NULL,
    `is_active` tinyint DEFAULT NULL,
    `raw_payload` clob DEFAULT NULL,
    `match_status` varchar(32) NOT NULL,
    `matched_product_sku_id` varchar(64) DEFAULT NULL,
    `merged_store_product_id` varchar(64) DEFAULT NULL,
    `last_sync_time` timestamp DEFAULT NULL,
    `matched_time` timestamp DEFAULT NULL,
    `merged_time` timestamp DEFAULT NULL,
    `conflict_reason` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `unique_deleted` bigint NOT NULL DEFAULT 0,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_ele_store_goods_shadow_biz` ON `ele_store_goods_shadow` (`tenant_id`, `platform_id`, `merchant_code`, `erp_store_code`, `sku_code`, `unique_deleted`);
CREATE INDEX IF NOT EXISTS `idx_ele_store_goods_shadow_store_status` ON `ele_store_goods_shadow` (`store_id`, `match_status`, `deleted`);
CREATE INDEX IF NOT EXISTS `idx_ele_store_goods_shadow_platform_status` ON `ele_store_goods_shadow` (`platform_id`, `erp_store_code`, `match_status`, `deleted`);
CREATE INDEX IF NOT EXISTS `idx_ele_store_goods_shadow_sku_status` ON `ele_store_goods_shadow` (`sku_code`, `match_status`, `deleted`);
CREATE INDEX IF NOT EXISTS `idx_ele_store_goods_shadow_status_time` ON `ele_store_goods_shadow` (`match_status`, `update_time`, `deleted`);

CREATE TABLE IF NOT EXISTS `store_table` (
    `store_id` varchar(64) NOT NULL,
    `store_name` varchar(255) DEFAULT NULL,
    `region_code` varchar(64) DEFAULT NULL,
    `address` varchar(500) DEFAULT NULL,
    `area` varchar(64) DEFAULT NULL,
    `store_status` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`store_id`)
);

CREATE TABLE IF NOT EXISTS `store_space_table` (
    `store_space_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` varchar(64) DEFAULT NULL,
    `building_area` decimal(24, 6) DEFAULT NULL,
    `cold_storage_area` decimal(24, 6) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`store_space_id`)
);
CREATE INDEX IF NOT EXISTS `idx_store_space_table_store_id` ON `store_space_table` (`store_id`);

CREATE TABLE IF NOT EXISTS `store_affiliation_table` (
    `affiliation_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` varchar(64) DEFAULT NULL,
    `business_mode` varchar(64) DEFAULT NULL,
    `store_type` varchar(64) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`affiliation_id`)
);
CREATE INDEX IF NOT EXISTS `idx_store_affiliation_table_store_id` ON `store_affiliation_table` (`store_id`);

CREATE TABLE IF NOT EXISTS `store_business_status_table` (
    `store_business_status_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` varchar(64) DEFAULT NULL,
    `current_status` varchar(64) DEFAULT NULL,
    `open_date` date DEFAULT NULL,
    `sign_date` date DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`store_business_status_id`)
);
CREATE INDEX IF NOT EXISTS `idx_store_business_status_table_store_id` ON `store_business_status_table` (`store_id`);

CREATE TABLE IF NOT EXISTS `store_franchisee_table` (
    `franchisee_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` varchar(64) DEFAULT NULL,
    `franchisee_name` varchar(255) DEFAULT NULL,
    `franchisee_phone` varchar(64) DEFAULT NULL,
    `franchisee_fee` decimal(24, 6) DEFAULT NULL,
    `security_deposit` decimal(24, 6) DEFAULT NULL,
    `contract_start` date DEFAULT NULL,
    `contract_end` date DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`franchisee_id`)
);
CREATE INDEX IF NOT EXISTS `idx_store_franchisee_table_store_id` ON `store_franchisee_table` (`store_id`);

CREATE TABLE IF NOT EXISTS `store_contact_table` (
    `contact_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` varchar(64) DEFAULT NULL,
    `contact_name` varchar(255) DEFAULT NULL,
    `contact_type` varchar(64) DEFAULT NULL,
    `contact_role` varchar(64) DEFAULT NULL,
    `phone` varchar(64) DEFAULT NULL,
    `is_primary` int DEFAULT NULL,
    `status` int DEFAULT NULL,
    `remark` varchar(500) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`contact_id`)
);
CREATE INDEX IF NOT EXISTS `idx_store_contact_table_store_id` ON `store_contact_table` (`store_id`);

CREATE TABLE IF NOT EXISTS `platform_table` (
    `platform_id` bigint NOT NULL,
    `platform_code` varchar(20) DEFAULT NULL,
    `platform_name` varchar(50) DEFAULT NULL,
    `platform_type` varchar(20) DEFAULT NULL,
    `status` int DEFAULT NULL,
    `sort_order` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`platform_id`)
);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_platform_table_code` ON `platform_table` (`platform_code`, `deleted`);

CREATE TABLE IF NOT EXISTS `store_platform_table` (
    `store_platform_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `store_id` varchar(64) DEFAULT NULL,
    `platform_id` bigint DEFAULT NULL,
    `platform_store_id` varchar(50) DEFAULT NULL,
    `platform_store_name` varchar(100) DEFAULT NULL,
    `agent_type` varchar(64) DEFAULT NULL,
    `commission_rate` decimal(24, 6) DEFAULT NULL,
    `settlement_account` varchar(100) DEFAULT NULL,
    `status` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`store_platform_id`)
);
CREATE INDEX IF NOT EXISTS `idx_store_platform_table_store_id` ON `store_platform_table` (`store_id`);
CREATE INDEX IF NOT EXISTS `idx_store_platform_table_platform_id` ON `store_platform_table` (`platform_id`);

CREATE TABLE IF NOT EXISTS `warehouse_table` (
    `warehouse_id` varchar(64) NOT NULL,
    `warehouse_code` varchar(64) DEFAULT NULL,
    `warehouse_name` varchar(255) DEFAULT NULL,
    `warehouse_type` varchar(64) DEFAULT NULL,
    `region_code` varchar(64) DEFAULT NULL,
    `address` varchar(500) DEFAULT NULL,
    `warehouse_status` int DEFAULT NULL,
    `is_default` int DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 1,
    PRIMARY KEY (`warehouse_id`)
);
CREATE INDEX IF NOT EXISTS `idx_warehouse_table_warehouse_name` ON `warehouse_table` (`warehouse_name`);

CREATE TABLE IF NOT EXISTS `warehouse_store_supply` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `warehouse_id` varchar(64) NOT NULL,
    `store_id` varchar(64) NOT NULL,
    `is_primary` int NOT NULL DEFAULT 0,
    `supply_status` int NOT NULL DEFAULT 1,
    `remark` varchar(255) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
);
CREATE INDEX IF NOT EXISTS `idx_warehouse_store_supply_warehouse_id` ON `warehouse_store_supply` (`warehouse_id`);
CREATE INDEX IF NOT EXISTS `idx_warehouse_store_supply_store_id` ON `warehouse_store_supply` (`store_id`);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_warehouse_store_supply_pair` ON `warehouse_store_supply` (`warehouse_id`, `store_id`, `deleted`);

CREATE TABLE IF NOT EXISTS `warehouse_line` (
    `line_id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `warehouse_id` varchar(64) NOT NULL,
    `line_code` varchar(64) NOT NULL,
    `line_name` varchar(128) NOT NULL,
    `order_weekdays` varchar(32) NOT NULL,
    `line_status` int NOT NULL DEFAULT 1,
    `remark` varchar(255) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`line_id`)
);
CREATE INDEX IF NOT EXISTS `idx_warehouse_line_warehouse_id` ON `warehouse_line` (`warehouse_id`);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_warehouse_line_code` ON `warehouse_line` (`warehouse_id`, `line_code`, `deleted`);

CREATE TABLE IF NOT EXISTS `warehouse_line_store` (
    `id` bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `line_id` bigint NOT NULL,
    `store_id` varchar(64) NOT NULL,
    `sort_no` int DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`id`)
);
CREATE INDEX IF NOT EXISTS `idx_warehouse_line_store_line_id` ON `warehouse_line_store` (`line_id`);
CREATE INDEX IF NOT EXISTS `idx_warehouse_line_store_store_id` ON `warehouse_line_store` (`store_id`);
CREATE UNIQUE INDEX IF NOT EXISTS `uk_warehouse_line_store_pair` ON `warehouse_line_store` (`line_id`, `store_id`, `deleted`);
