CREATE TABLE IF NOT EXISTS `tag_dimension` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `domain_type` varchar(32) NOT NULL COMMENT '对象域 PRODUCT/STORE/MEMBER',
  `parent_id` bigint NOT NULL DEFAULT 0 COMMENT '父级维度 ID',
  `level` tinyint NOT NULL COMMENT '层级 1/2/3',
  `name` varchar(100) NOT NULL COMMENT '维度名称',
  `code` varchar(100) NOT NULL COMMENT '维度编码',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 0停用 1启用',
  `description` varchar(500) DEFAULT NULL COMMENT '说明',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `unique_deleted` bigint NOT NULL DEFAULT 0 COMMENT '未删除为0，删除后用于释放唯一键',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tag_dimension_parent_code` (`tenant_id`, `domain_type`, `parent_id`, `code`, `unique_deleted`),
  KEY `idx_tag_dimension_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='标签维度表';

CREATE TABLE IF NOT EXISTS `tag_value` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `dimension_id` bigint NOT NULL COMMENT '所属 L3 维度 ID',
  `name` varchar(100) NOT NULL COMMENT '标签值名称',
  `code` varchar(100) NOT NULL COMMENT '标签值编码',
  `tag_method` varchar(32) NOT NULL COMMENT '打标方式',
  `data_source` varchar(200) DEFAULT NULL COMMENT '数据源',
  `update_frequency` varchar(100) DEFAULT NULL COMMENT '更新频率',
  `logic_description` varchar(1000) DEFAULT NULL COMMENT '打标逻辑说明',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 0停用 1启用',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `unique_deleted` bigint NOT NULL DEFAULT 0 COMMENT '未删除为0，删除后用于释放唯一键',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tag_value_dimension_code` (`tenant_id`, `dimension_id`, `code`, `unique_deleted`),
  KEY `idx_tag_value_dimension` (`dimension_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='标签值表';

CREATE TABLE IF NOT EXISTS `tag_virtual` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `domain_type` varchar(32) NOT NULL COMMENT '对象域 PRODUCT/STORE/MEMBER',
  `name` varchar(100) NOT NULL COMMENT '虚拟标签名称',
  `code` varchar(100) NOT NULL COMMENT '虚拟标签编码',
  `expression_json` longtext NOT NULL COMMENT '表达式 JSON',
  `expression_summary` varchar(1000) DEFAULT NULL COMMENT '表达式摘要',
  `usage_scenario` varchar(500) DEFAULT NULL COMMENT '使用场景',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 0停用 1启用',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `unique_deleted` bigint NOT NULL DEFAULT 0 COMMENT '未删除为0，删除后用于释放唯一键',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tag_virtual_domain_code` (`tenant_id`, `domain_type`, `code`, `unique_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='虚拟标签表';
